#!/usr/bin/python3
#Copyright 2011 Matthew J. Smith (matt@forsetti.com)
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at

#  http://www.apache.org/licenses/LICENSE-2.0

#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

import os
import sys
import re
import socketserver
import threading
import random

class ThreadedUDPServer(socketserver.ThreadingMixIn, socketserver.UDPServer):
	"""Simple class to create a Threaded UDP Server by mixing the
	ThreadingMixIn and UDPServer."""
	pass

class ThreadedTCPServer(socketserver.ThreadingMixIn, socketserver.TCPServer):
	"""Simple class to create a Threaded TCP Server by mixing the
	ThreadingMixIn and TCPServer."""
	pass

class TCPDNSHandler(socketserver.BaseRequestHandler):
	"""socketserver TCP handler.  Reads DNS request size from first two
	bytes of stream, then passes remaining message to resolver.  Upon
	receiving response, writes 2 byte size of response and response.
	"""
	def handle(self):
		request=bytes()
		size_header=self.request.recv(2)
		size=(size_header[0]<<8)+size_header[1]
		while(size>0):
			request+=self.request.recv(size)
			size-=len(request)
		response=self.server.resolver.resolve(request)
		size=len(response)
		self.request.send(bytes([size>>8,size%256]))
		self.request.send(response)
		self.request.close()

class UDPDNSHandler(socketserver.BaseRequestHandler):
	"""socketserver UDP handler.  Passes DNS request to resolver, and
	returns response."""
	def handle(self):
		request = self.request[0]
		sock = self.request[1]
		response=self.server.resolver.resolve(request)
		if(len(response)>512):
			response[2]|=0x02
		sock.sendto(response[:512], self.client_address)

class CommandController():
	"""CommandController accepts a single "commander" object at construction time,
	then upon call to handle(in,out) parses an input stream into line-delimited
	commands, with each command parsed into space-delimited operation
	and parameters, then calls each operation as a method on commander,
	passing the parameters to the method.  Any strings returned are
	passed to the output stream.  The final line returned after each
	command a numeric code follwed by a single-word error name in
	parens, e.g. "3: (ERROR)"."""
	def __init__(self,commandlet):
		self.commandlet=commandlet
		
	def handle(self,instream, outstream):
		while True:
			try:
				outstream.write("\n> ".encode())
				outstream.flush()
				line=instream.readline().decode()

				if(not line): return #EOF
				command=line.strip().split()
				if(len(command)==0): continue #Blank Line
				if(command[0]=="?" and len(command)==1): #? = Print Help - all function names and docstrings
					outstream.write(("0 (OK)\nUse \"? <command>\" for help on a specific command: "+(", ".join([a for a in dir(self.commandlet) if(re.match("^[a-zA-Z][a-zA-Z0-9_]*$",a))]))).encode())
				elif(command[0]=="?" and len(command)==2):
					import inspect
					f=getattr(self.commandlet,command[1])
					args=inspect.getfullargspec(f)[0]
					doc=getattr(self.commandlet,command[1]).__doc__
					if(not doc): doc="No documentation available"
					s=command[1]+" "+" ".join(["[%s]"%(a) for a in args if a!="self"])+" : "+doc
					outstream.write(("0 (OK)\n"+s).encode())
				#All commands must start with a letter, and be followed with alpha, num, or _
				elif(not re.match("^[a-zA-Z][a-zA-Z0-9_]*$",command[0])): raise AttributeError()
				else:
					#Try call of command on commandlet, throws AttributeError if not valid
					s=getattr(self.commandlet,command[0])(*command[1:])
					if(not s):s=""
					outstream.write(("0 (OK)\n%s\n"%(s)).encode())
			except AttributeError as e:
				outstream.write("2 (INVALID)\nInvalid Command".encode())
			except TypeError as e:
				print(e)
				outstream.write("4 (PARAMS)\nInvalid Parameters".encode())
			except Exception as e:
				print("***")
				import traceback
				traceback.print_exc()
			finally:
				outstream.flush()

class CNamedCommander():
	"""Provides methods to update, query, and control the resolver."""
	def __init__(self,resolver):
		self.__data__=dict()
		self.__resolver__=resolver
		
	def echo(self,*args):
		"""Returns all arguments"""
		return(" ".join(args))
	
	def shutdown(self):
		"""Shutdown %s"""%(sys.argv[0])
		sys.exit(0)

	def alias(self, alias, hostname,weight):
		"""Adds an alias to hostname mapping with supplied weight and optional ttl (defaults to 0)"""
		self.__resolver__.update(alias,hostname,int(weight))
		
#	def dump(self):
#		"""Dump database in loadable format"""
#		return("".join(["alias %s\n"%(alias) for alias in self.data]))

	def listen(self, protocol,address, port):
		"""Start listener for protocol (udp|tcp) on address:port"""
		port=int(port)
		if(protocol=="udp"):
			udpServer = ThreadedUDPServer((address, port), UDPDNSHandler)
			udpServer.resolver=self.__resolver__
			udp_thread = threading.Thread(target=udpServer.serve_forever)
			udp_thread.setDaemon(True)
			udp_thread.start()
		elif(protocol=="tcp"):
			tcpServer = ThreadedTCPServer((address, port), TCPDNSHandler)
			tcpServer.resolver=self.__resolver__
			tcp_thread = threading.Thread(target=tcpServer.serve_forever)
			tcp_thread.setDaemon(True)
			tcp_thread.start()
		else:
			raise(TypeError())
		
class USSHandler(socketserver.StreamRequestHandler):
	"""UnixStreamServer handler to connect the socket stream to the 
	CommandController for interactive control of CNameD."""
	def handle(self):
		self.server.controller.handle(self.rfile,self.wfile)
		
class UnixStreamServer(socketserver.UnixStreamServer):
	"""Local UnixStreamServer to override handle_error()."""
	def handle_error(self, request,client_address):
		"""If exception is thrown by child thread, rethrow in main"""
		ei=sys.exc_info()
		if(ei[1]): raise(ei[1])
		print(sys.exc_info())
		
class Resolver():
	"""Does the heavy lifting of encoding/decoding and resolving queries.
	"""
	def __init__(self):
		self.__data__=dict()

	def update(self,qname,rname,weight):
		question=self.encode_name(qname)
		answer=self.encode_answer(question,rname)
		self.__data__[question]=[a for a in self.__data__.get(question,list()) if a!=answer]
		self.__data__[question]+=[answer]*weight
			
	def encode_name(self, name):
		labels=name.split(".")

		enc=bytes(0)
		for label in labels:
			assert(len(label)<=63)
			enc+=bytes([len(label)])+label.encode()
		enc+=bytes([0])
		return(enc)

	def decode_name(self, name):
		i=0
		domainname=""
		while(name[i]):
			next=i+name[i]+1
			domainname+=name[i+1:next].decode()+"."
			i=next
		return(domainname[:-1]) #Drop trailing period

	def encode_answer(self,eqname,rname):
		ername=self.encode_name(rname)
		size=len(ername)
		#RR is encoded qname+TYPE=CNAME+CLASS=IN+TTL=0+size(encoded name)+encoded name
		return(eqname+bytes([0x00,0x05,0x00,0x01,0x00,0x00,0x00,0x00])+bytes([size>>8,size%256])+ername)

	def resolve(self,request):
		header=bytearray(request[0:12])
		question=request[12:]
		if ( not((header[2]&0x80 == 0) and (header[2]&0x78 == 0 ) and (header[3]&0x70 == 0 ))): #qr=query && opcode=QUERY  && Z=0
			header[2]|= 0x84 #set QR,AA flags
			header[2]&= 0x87 #clr OPCODE,TC
			header[3] =0x01  #set RCODE=1,clr RA,Z
			response=header+question
			return(response)
			
		header[2]|= 0x84 #set QR,AA
		header[2]&= 0xFD #clr TC
		header[3] = 0x00 #clr RA,Z,RCODE
		header[6:12]=[0x00,0x01,0x00,0x00,0x00,0x00] #Set ANCOUNT=1

		#Validate QCLASS=IN and QTYPE=A or QTYPE=CNAME
		if(question[-4]==0 and question[-2]==0 and question[-1]==1 and (question[-3]==1 or question[-3]==5)):
			answers=self.__data__.get(question[:-4])
			if(answers):
				response=header+question+random.choice(answers)
			else:
				header[3]|=0x03
				response=header+question
		else:
			header[3]|=0x04
			response=header+question
		
		return(response)


if __name__ == "__main__":
	sockpath=None
	ussServer=None
	if(len(sys.argv)==2):
		sockpath=sys.argv[1]
		ussServer=UnixStreamServer(sockpath,USSHandler)
		ussServer.controller=CommandController(CNamedCommander(Resolver()))
		try:
			ussServer.serve_forever()
		except KeyboardInterrupt:
			print("Keyboard shutdown (^C) detected.")
		except SystemExit:
			print("Shutdown requested")
		finally:
			if(sockpath):os.unlink(sockpath)
			if(ussServer):ussServer.server_close()
	else:
		try:
			c=CommandController(CNamedCommander(Resolver())).handle(sys.stdin.buffer,sys.stdout.buffer)
		except KeyboardInterrupt:
			print("Keyboard shutdown (^C) detected.")		
		except SystemExit:
			print("Shutdown requested")
	exit(0)
			
